// Project actions
export const TOGGLE_PROJECT_FORM = 'TOGGLE_PROJECT_FORM';
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_PROJECT_FORM = 'VALIDATE_PROJECT_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';